### ISSUE TITLE
Poor connection after a disconnect?

### ISSUE THREAD

**Issue by czarina** [al177/esp8089#10]
I have a Pi Zero and have followed these instructions, which include this repo, to hook an ESP8266 to it: https://hackaday.io/project/8678/instructions

The ESP is currently connected to the internet via my home router. I'm testing what happens if I turn the router off and then back on. The ESP does seem to automatically re-establish a connection once the router finishes rebooting, but the new connection has very poor upload/download speeds compared to the original connection, and I'm unsure why. It's nothing wrong with my router, as my desktop shows normal speeds from the router after it is restarted.

If I restart my router, I'd like the ESP to reconnect and the new connection should be just as good as before.

Any suggestions?

**Comment by al177** [comment]
Do you have a USB-WiFi dongle to try with your Pi Zero to rule out the ESP8266 and the esp8089 driver?  It could also be something to do with Raspbian's wpa-supplicant setup and your particular router.

I have brought up and down connections repeatedly on the ESP8266 end with no issues reconnecting at the original rates, though I haven't done any throughput tests before and after rebooting the router.
