### ISSUE TITLE
Can I use this driver via SD card slot?

### ISSUE THREAD

**Issue by iwamatsu** [al177/esp8089#27]
Hi,

I would like to run SDIO's WIFI on SDHCI host controller which supported SDIO.
Can I run this driver with SDHCI host controller? Is it supported only via GPIO?

Best regards,
  Nobuhiro

**Comment by al177** [comment]
This driver should work through a card slot as long as the host supports SDIO.  Since there is no reset available on an SD slot, CH_PD and RST should be wired to deassert (pulled up) on power-up since SD and SDIO perform device reset by cycling power.
