### ISSUE TITLE
Integration with kernel tree

### ISSUE THREAD

**Issue by pablogs9** [al177/esp8089#28]
I'm trying to compile this module for a embedded device including it in our kernel tree branch. Does anyone knows how must be the Makefile rewriten to be included in Kbuild system and the .ko files generated for MODPOST?

**Comment by al177** [comment]
The original driver this is based on is an in-tree driver released as part of Rockchip tablet kernel sources.  If you look at the earliest few commits, you can see where I converted the in kernel driver into a module.

**Comment by CRImier** [comment]
@pablogs9 you will likely want to see this commit: https://github.com/Icenowy/esp8089/commit/5586b6aac8e7e7da4b0b8439e9c3876f11d8da90

**Comment by zoobab** [comment]
What about submitting this linux driver upstream?

**Comment by al177** [comment]
@zoobab I would love to see this mainlined, but I don't have any experience doing so.  Given the trouble others with more experience have had in getting this driver accepted, I don't think this is the driver to cut my upstream submission teeth on.
