### ISSUE TITLE
How to configure AP mode?

### ISSUE THREAD

**Issue by congcongge** [al177/esp8089#33]
Hello, I have completely bulid this driver and successfully use it in my board, but i don't know how to configure AP mode, can you give some direction? Eagerly  wait for your reply, thx.

**Comment by congcongge** [comment]
Is anyone here? Ask for help....

**Comment by al177** [comment]
Sorry for the delay, busy with work at the moment.

The driver supports AP mode, but you will need something like hostapd running to service the AP.

The [hostapd section of this guide](https://www.raspberrypi.org/documentation/configuration/wireless/access-point.md) is directly applicable to working with this driver.

**Comment by congcongge** [comment]
> Sorry for the delay, busy with work at the moment.
> 
> The driver supports AP mode, but you will need something like hostapd running to service the AP.
> 
> The [hostapd section of this guide](https://www.raspberrypi.org/documentation/configuration/wireless/access-point.md) is directly applicable to working with this driver.

谢谢大神指点！万分感谢。
