### ISSUE TITLE
Any reason not to work on kernel 5.4.51 ?

### ISSUE THREAD

**Issue by amateusz** [al177/esp8089#43]
I compiled the module on current stable (5.4.51 as of July 2020) and it doesn't seem to work. I confirmed it working on 4.9 some time ago on the same HW (RPi A+ with soldered ESP-12F).

Could you confirm it's not working on kernels ≥5 ?

---

By the way thank you for your work. I've spotted your pants project on hackaday some long time ago and finally made one myself few months ago

**Comment by al177** [comment]
I just tried a fresh install on a Pi 2B of Raspbian Lite and the release 1.9.20190603 deb and it appears to be working on the latest kernel 5.4.51-v7+.

However I haven't tried on an armv6 platform. Can you elaborate on what's not working?

**Comment by amateusz** [comment]
I confirm it works on 5.4.51+ armv6.

The problem was missing `dtoverlay=sdio,poll_once=off` in `config.txt`. Found the tip in [your hackaday.io instructions](https://hackaday.io/project/8678-rpi-wifi). 
Maybe consider adding it to readme?

Sorry for the fuss.

---

**"Retro" RPi 1A going strong:**
![IMG_0753](https://user-images.githubusercontent.com/9356928/93531121-ff9d2a00-f93e-11ea-9c29-f166f416004f.jpg)

**Comment by al177** [comment]
Thanks for letting me know, and glad you got it working!
