### ISSUE TITLE
Hidden SSID connection problem

### ISSUE THREAD

**Issue by ghost** [al177/esp8089#48]
Hi.
First i tried your module, but it failed to init:
```
esp_readwrite_file: file /system/lib/modules/test_results filp_open error
first normal exit
esp_sdio_remove enter
eagle_sdio: probe of mmc1:0001:1 failed with error -110
```
then i tried @Icenowy fork: https://github.com/Icenowy/esp8089/tree/cleanup
it worked, but cannot connect to hidden SSID!

**Comment by al177** [comment]
Sorry this issue got stale, but it looks like the device didn't boot the firmware payload. There are a lot of reasons for that, and it's not clear why the fork completes fw boot but fails to access a hidden SSID. In general most of the problems I've seen here are signal integrity related, which can manifest as a variety of issues.

If this is still something you want to work through, please reopen as a fresh issue and include more detail (platform, kernel, more logs, SDIO traffic during the failure ( https://community.silabs.com/s/article/linux-sdio-detection?language=en_US ), and the ESP module type and how it's attached to the platform)
