### ISSUE TITLE
'no .config found' on install?

### ISSUE THREAD

**Issue by czarina** [al177/esp8089#7]
This is the error I get on 'make sudo make install':

Makefile:19: *** No .config found in /lib/modules/4.4.34+/build, please set KBUILD to configured kernel.  Stop.

**Comment by al177** [comment]
The ideal way to install this is via DKMS, which will handle building the module against the current kernel.  Follow the directions here: [https://hackaday.io/project/8678/instructions](https://hackaday.io/project/8678/instructions)

If you want to build directly from this git repo, you'll need to install the matching kernel headers, which Raspbian doesn't provide in package form.  [rpi-source is a good tool](https://github.com/notro/rpi-source/wiki) for fetching and configuring the source tree matching the currently running kernel.

**Comment by al177** [comment]
@czarina : Please update this issue when youve had a chance to try one of the above suggestions.  If the KBUILD process is broken due to some change in Raspbian I'd like to fix it.
